sudo: true
language: haskell

git:
  depth: 5

cabal: "head"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.6.5

install:
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks

notifications:
  email: false
